baseURL                 = "https://correlaid.org/"

DefaultContentLanguage  = "de"

PygmentsCodeFences      = true
PygmentsStyle           = "friendly"
enableEmoji             = true 

[params]
    twitter         = "https://twitter.com/CorrelAid"
    facebook        = "https://facebook.com/WeAreCorrelAid"
    linkedin        = "https://www.linkedin.com/company/correlaid/"
    
[Languages]
[Languages.en]
    contentDir      = "content/en"
    title           = "CorrelAid"
    weight          = 0
    languageName    = "English"
    [Languages.en.params]
        [Languages.en.params.navigation]
            about   = "About"

[Languages.de]
    contentDir      = "content/de"
    title           = "CorrelAid"
    weight          = 0
    languageName    = "Deutsch"
    [Languages.de.params]
            [Languages.de.params.navigation]
                about   = "Über uns"


[taxonomies]
  category = "categories"
  tag = "tags"
  language = "languages"


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    simple = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[services]
  [services.twitter]
    disableInlineCSS = false