baseURL                 = "https://correlaid.org/"

DefaultContentLanguage  = "de"
DefaultContentLanguageInSubdir = false

PygmentsCodeFences      = true
PygmentsStyle           = "friendly"
enableEmoji             = true 
[params]
    twitter         = "https://twitter.com/CorrelAid"
    facebook        = "https://facebook.com/WeAreCorrelAid"
    linkedin        = "https://www.linkedin.com/company/correlaid/"
    num_members     = "1900"
    mailinglist_volunteers = "https://correlaid.us12.list-manage.com/subscribe?u=b294bf2834adf5d89bdd2dd5a&id=915f3f3eff"
    mailinglist_npos = "https://correlaid.us12.list-manage.com/subscribe?u=b294bf2834adf5d89bdd2dd5a&id=175fade988"
    author = "CorrelAid e.V."
    [params.description] 
      de = "CorrelAid ist ein überparteiliches, gemeinnütziges Netzwerk von über 1700 Data-Science-begeisterten Menschen, die die Welt mithilfe von Data Science verändern wollen.  Unsere Arbeit richtet sich an den sozialen Sektor und Organisationen, die sich dafür einsetzen, die Welt zu einem besseren Ort zu machen." 
      en = "CorrelAid is a non-partisan non-profit network of over 1700 data science enthusiasts who want to change the world through data science. We dedicate our work to the social sector and those organizations that strive for making the world a better place."
[Languages]
# duplicate en settings to both get correlaid.org/en/projects and correlaid.org/projects 
# see https://discourse.gohugo.io/t/default-language-in-both-root-and-subfolders/17531/3
[Languages.en]
    contentDir      = "content/en"
    title           = "CorrelAid"
    weight          = 0
    languageName    = "English"
    [Languages.en.params]
        [Languages.en.params.navigation]
            about   = "About"
[Languages.de2]
    contentDir      = "content/de"
    title           = "CorrelAid"
    weight          = 0
    languageName    = "Deutsch"
    [Languages.de2.params]
        [Languages.de2.params.navigation]
            about   = "Über uns"
[Languages.de]
    contentDir      = "content/de"
    title           = "CorrelAid"
    weight          = 1
    languageName    = "Deutsch"
    [Languages.de.params]
            [Languages.de.params.navigation]
                about   = "Über uns"


[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
    
[taxonomies]
  category = "categories"
  tag = "tags"
  language = "languages"


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    simple = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[services]
  [services.twitter]
    disableInlineCSS = false

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"
