baseURL                 = "https://correlaid.org/"

DefaultContentLanguage  = "en"
DefaultContentLanguageInSubdir = true

PygmentsCodeFences      = true
PygmentsStyle           = "friendly"
[params]
    twitter         = "https://twitter.com/CorrelAid"
    facebook        = "https://facebook.com/WeAreCorrelAid"
    linkedin        = "https://www.linkedin.com/company/correlaid/"
    
[Languages]
[Languages.en]
    contentDir      = "content/en"
    title           = "CorrelAid"
    weight          = 0
    languageName    = "English"
    [Languages.en.params]
        [Languages.en.params.navigation]
            about   = "About"

[Languages.de]
    contentDir      = "content/de"
    title           = "CorrelAid"
    weight          = 1
    languageName    = "Deutsch"
    [Languages.de.params]
            [Languages.de.params.navigation]
                about   = "Über uns"


[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"